services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: esettlement-db
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
    volumes:
      - ./datadb/postgres_data:/var/lib/postgresql/data
    networks:
      esettlement-network:
        ipv4_address: 172.19.0.2
    ports:
      - "5432:5432"

  postgres-replica:
    build:
      context: .
      dockerfile: Dockerfile.db-replica
    container_name: esettlement-db-replica
    depends_on:
      - postgres
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=172.19.0.2
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - ./datadb/postgres_replica_data:/var/lib/postgresql/data
    networks:
      esettlement-network:
        ipv4_address: 172.19.0.3
    ports:
      - "5433:5432"

  pgadmin:
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    container_name: esettlement-pgadmin
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      esettlement-network:
        ipv4_address: 172.19.0.4
    ports:
      - "5440:80"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: esettlement-api
    depends_on:
      - postgres
    networks:
      esettlement-network:
        ipv4_address: 172.19.0.9
    ports:
      - "8081:8081"
    command: >
      bash -c "mvn --version &&
        mvn clean compile exec:java -Dexec.mainClass="org.ossfmct.projects.EsettlementApi" -Dspring.datasource.url=jdbc:postgresql://172.19.0.2:5432/esettlement_db"

networks:
  esettlement-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

volumes:
  pgadmin_data:

