spring:
  config:
    import: "optional:file:.env[.properties]"
  
  application:
    name: builder-service

  # KAFKA PROPERTIES
  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS}

    # KAFKA PRODUCER PROPERTIES
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    
    # KAFKA CONSUMER PROPERTIES
    consumer:
      group-id: builder-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "org.settlehub.*" 
        spring.json.use.type.headers: true

  # DATABASE PROPERTIES
  datasource:
    url: ${BUILDER_DB_URL:jdbc:postgresql://localhost:5432/builder-service-db?sslmode=disable}
    username: ${BUILDER_DB_USERNAME}
    password: ${BUILDER_DB_PASSWORD}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        enable_lazy_load_no_trans: true
        format_sql: false

server:
  port: 8004
  http2:
    enabled: true
  servlet:
    context-path: /builder/api

# LOGGING
logging:
  file:
    name: logs/builder-service.log
    path: logs

# EUREKA DISCOVERY SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_ADDRESS:localhost:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: ${BUILDER_SERVICE_IP:127.0.0.1}
