name: Notification Pipeline

on:
  push:
    paths: ['services/notification/**']
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image'
        required: true
        default: 'latest'

jobs:
  ci:
    uses: ./.github/workflows/templates/java-ci.yml
    with:
      working-directory: services/notification
      service-name: notification-service
    secrets: inherit

  cd-publish:
    needs: [ci]
    uses: ./.github/workflows/templates/docker-cd.yml
    with:
      working-directory: services/notification
      image-name: notification-service
    secrets: inherit

  deploy:
    needs: [cd-publish]
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy compose.yml to Target Machine
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NOTIFICATION_SERVICE_DEPLOY_HOST }}
          username: ${{ secrets.NOTIFICATION_SERVICE_DEPLOY_USER }}
          key: ${{ secrets.NOTIFICATION_SERVICE_DEPLOY_SSH_KEY }}
          source: "services/notification/compose.yml"
          target: "/opt/settlehub/notification/"
          strip_components: 2 

      - name: Deploy to Target Machine via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          IMAGE_TAG: ${{ github.event.inputs.image_tag || 'latest' }}
          NOTIFICATION_DB_URL: ${{ secrets.NOTIFICATION_DB_URL }}
          NOTIFICATION_DB_USERNAME: ${{ secrets.NOTIFICATION_DB_USERNAME }}
          NOTIFICATION_DB_PASSWORD: ${{ secrets.NOTIFICATION_DB_PASSWORD }}
          KAFKA_ADDRESS: ${{ secrets.KAFKA_ADDRESS }}
          SMTP_SERVER_ADDRESS: ${{ secrets.SMTP_SERVER_ADDRESS }}
          SMTP_SERVER_PORT: ${{ secrets.SMTP_SERVER_PORT }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          EUREKA_ADDRESS: ${{ secrets.EUREKA_ADDRESS }}
          NOTIFICATION_SERVICE_IP: ${{ secrets.NOTIFICATION_SERVICE_IP }}
        with:
          host: ${{ secrets.NOTIFICATION_SERVICE_DEPLOY_HOST }}
          username: ${{ secrets.NOTIFICATION_SERVICE_DEPLOY_USER }}
          key: ${{ secrets.NOTIFICATION_SERVICE_DEPLOY_SSH_KEY }}
          envs: IMAGE_TAG,NOTIFICATION_DB_URL,NOTIFICATION_DB_USERNAME,NOTIFICATION_DB_PASSWORD,KAFKA_ADDRESS,SMTP_SERVER_ADDRESS,SMTP_SERVER_PORT,MAIL_USERNAME,MAIL_PASSWORD,EUREKA_ADDRESS,NOTIFICATION_SERVICE_IP
          script: |
            mkdir -p /opt/settlehub/notification/
            cd /opt/settlehub/notification/

            echo "NOTIFICATION_DB_URL=$NOTIFICATION_DB_URL" > .env
            echo "NOTIFICATION_DB_USERNAME=$NOTIFICATION_DB_USERNAME" >> .env
            echo "NOTIFICATION_DB_PASSWORD=$NOTIFICATION_DB_PASSWORD" >> .env
            echo "KAFKA_ADDRESS=$KAFKA_ADDRESS" >> .env
            echo "SMTP_SERVER_ADDRESS=$SMTP_SERVER_ADDRESS" >> .env
            echo "SMTP_SERVER_PORT=$SMTP_SERVER_PORT" >> .env
            echo "MAIL_USERNAME=$MAIL_USERNAME" >> .env
            echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .env
            echo "EUREKA_ADDRESS=$EUREKA_ADDRESS" >> .env
            echo "NOTIFICATION_SERVICE_IP=$NOTIFICATION_SERVICE_IP" >> .env
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/settlehub/notification-service:$IMAGE_TAG
            docker compose up -d
            docker image prune -a -f --filter "until=24h"